# Generated by Django 5.2.7 on 2025-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content_html", models.TextField()),
                ("content_text", models.TextField()),
                ("source_url", models.URLField(unique=True)),
                ("source_domain", models.CharField(db_index=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
